runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app
runtime_config:
  python_version: 2
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

- url: /static/(.*\.(pkl))$
  static_files: static/\1
  upload: static/.*\.(pkl)$

- url: /words
  script: main.app
